### ISSUE TITLE
Test-NexposeSearchCriteria cannot handle SearchCriteria with single filters

### ISSUE THREAD

**Issue by utopianit-base** [My-Random-Thoughts/Rapid7Nexpose#11]
In creating a dynamic asset group with a single filter on a custom_tag, line 146 errors due to the lack of a count method on the SearchCriteria object passed.

```
###################
$ReturnValue = New-Object -TypeName 'boolean[]' $($SearchCriteria.filters).Count
###################
```

Changed to the following with sanity checking and tests went well:

```
###################
$FiltersCount = $($SearchCriteria.filters).Count
If(-not $FiltersCount -and $SearchCriteria.filters) {
            $FiltersCount = 1
}
$ReturnValue = New-Object -TypeName 'boolean[]' $FiltersCount
###################
```

**Comment by My-Random-Thoughts** [comment]
Thanks for logging this, can you provide an example of your search criteria please.

**Comment by My-Random-Thoughts** [comment]
No response and I can't replicate the issue.  Happy to open it again if you still have problems.

**Comment by utopianit-base** [comment]
Sorry for delay. Busy with work. Example code that causes the failure below:

Assumes already connected to Security Console.

```
##########################START
# Create Search Criteria Entry
function Add-SearchCriteriaFilter {
            param (
                [string]$field,
                [string]$operator='is',
                $value)

            
            [PSCustomObject]$SetItem = @{}
            $SetItem.Add('field',$field)
            $SetItem.Add('operator',$operator)    
            $SetItem.Add('value',$value)          

            return New-Object -TypeName psobject -Property $SetItem
}
# Create final Dynamic Asset Group based on Tag of $PROJECTNAME
$filter = @()
$PROJECTNAME = 'MYTESTMATCH'
$filter += Add-SearchCriteriaFilter -field 'custom-tag' -operator 'is' -value $PROJECTNAME
$SearchCriteria = @{'match' = 'all'; 'filters' = $filter}

$DynamicAssetGroupName   = "TEST Dynamic Asset Group"
$NewAssetGroup = New-NexposeAssetGroup -Type dynamic -Name $DynamicAssetGroupName -SearchCriteria $SearchCriteria -Description "Test"
##########################END
```

# Result
```
New-Object : A constructor was not found. Cannot find an appropriate constructor for type boolean[].
At line:154 char:24
+  turnValue = New-Object -TypeName 'boolean[]' $($SearchCriteria.filter
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : CannotFindAppropriateCtor,Microsoft.PowerShell.Commands.NewObjectCommand
```

If more filters are added to the array, it works OK.
Thanks.

**Comment by My-Random-Thoughts** [comment]
That is strange, as running `Test-NexposeSearchCriteria -SearchCriteria $SearchCriteria` returns `Success`.
Let me look into what's going on.

**Comment by My-Random-Thoughts** [comment]
So, I have just build a brand new Nexpose environment
Connected to it using the one-liner as show in my [basic-usage](https://github.com/My-Random-Thoughts/Rapid7Nexpose#basic-usage) example and ran your code with zero changes and it worked perfectly.

I would ask if you are using the latest version of the module, but it's not been changed for a while :)

What environment are you running this code on?

**Comment by utopianit-base** [comment]
Thanks for looking at it.
I hope it's not something I've done elsewhere and apologies if that's the case as my version shouldn't have been changed and should be fairly recent (last few months).

I'm running on PS v5.1 on Windows 10.
I'll grab the latest repo version and try again.

**Comment by utopianit-base** [comment]
OK, latest repo and just testing using the private function Test-NexposeSearchCriteria.

...
Import-Module '.\Rapid7Nexpose-master\Rapid7Nexpose.psm1' -Force

# Create Search Criteria Entry
function Add-SearchCriteriaFilter {
            param (
                [string]$field,
                [string]$operator='is',
                $value)

            
            [PSCustomObject]$SetItem = @{}
            $SetItem.Add('field',$field)
            $SetItem.Add('operator',$operator)    
            $SetItem.Add('value',$value)          

            return New-Object -TypeName psobject -Property $SetItem
}
# Create final Dynamic Asset Group based on Tag of $PROJECTNAME
$filter = @()
$PROJECTNAME = 'MYTESTMATCH'
$filter += Add-SearchCriteriaFilter -field 'custom-tag' -operator 'is' -value $PROJECTNAME
$SearchCriteria = @{'match' = 'all'; 'filters' = $filter}

Import-Module '.\Rapid7Nexpose-master\Private\Test-NexposeSearchCriteria.ps1'
Test-NexposeSearchCriteria -SearchCriteria $SearchCriteria
...

#Result
...
New-Object : A constructor was not found. Cannot find an appropriate constructor for type boolean[].
At [redacted]\Rapid7Nexpose-master\Private\Test-NexposeSearchCriteria.ps1:146 char:24
+ ... turnValue = New-Object -TypeName 'boolean[]' $($SearchCriteria.filter ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : CannotFindAppropriateCtor,Microsoft.PowerShell.Commands.NewObjectCommand
 
Cannot index into a null array.
At [redacted]\Rapid7Nexpose-master\Private\Test-NexposeSearchCriteria.ps1:154 char:13
+             $ReturnValue[$ReturnCounter] = $false
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
Cannot index into a null array.
At [redacted]\Rapid7\Rapid7Nexpose-master\Private\Test-NexposeSearchCriteria.ps1:179 char:33
+                                 $ReturnValue[$ReturnCounter] = $true
+                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
Cannot index into a null array.
At [redacted]\Rapid7Nexpose-master\Private\Test-NexposeSearchCriteria.ps1:220 char:25
+ ...         If (($ReturnValue[$ReturnCounter] -eq $true) -and ($operators ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
Cannot index into a null array.
At [redacted]\Rapid7\Rapid7Nexpose-master\Private\Test-NexposeSearchCriteria.ps1:246 char:19
+             If ($($ReturnValue[$ReturnCounter]) -eq $false) {
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
Success
...

If you add another filter into the array via:
...
$filter += Add-SearchCriteriaFilter -field 'custom-tag' -operator 'is' -value 'BLAH'
...

and then run it again.

#Result
...
Success
...

**Comment by utopianit-base** [comment]
(Sorry about the editing and reformatting...corporate proxy has issues with GitHub JS for some reason)

**Comment by My-Random-Thoughts** [comment]
No worries about the formatting.  I am running my code on Ubuntu with PowerShell 7.  Again though I am getting a success message running your initial code.

Let me build a Windows 10 box and try it on there.

**Comment by utopianit-base** [comment]
At least I'm not going insane then. :)

It is odd, but Windows still reports success but has the errors about the null array. I'm guessing it's just the different way that PowerShell and PowerShell dotNet Core handle variables of an array type that only have a single element.

I must admit, I'm regularly having to compensate for this from other Commandlets where they may return a single element rather than an array, because with one object returned, it becomes the single object type (string, or whatever) and doesn't have a .count method like an array. You'd think it would still be an array with a .count of 1, as it would in other languages.

**Comment by My-Random-Thoughts** [comment]
All fixed, thank you for finding this bug and for supplying a fix.  Very much appreciated.

**Comment by utopianit-base** [comment]
My pleasure. Thank you and the other contributors for creating such a great API!
It's made my work with Rapid7 a lot easier and has been invaluable in prioritising of security compliance for a 20,000 device estate.
I made an open source PowerShell API client for the AppCheckNG application vulnerability scanner a little while ago too.
