### ISSUE TITLE
Can't create New-NexposeTag  when type is set to "OWNERS"

### ISSUE THREAD

**Issue by naimco** [My-Random-Thoughts/Rapid7Nexpose#12]
**Describe the bug**
The New-NexposeTag function is not able to create a new tag when the type is "owner"  Tags are created when Type = custom.
I made sure my account has the proper permission but creating an owner tag from the webinterface.  

**To Reproduce**
 New-NexposeTag -Name "test" -Type "owners" -Colour "Default" -Debug

DEBUG: ApiQuery:
{
    "name":  "test",
    "color":  "default",
    "searchCriteria":  null,
    "type":  "owners"
}
The remote server returned an error: (400) Bad Request.
{
  "status" : 400,
  "message" : "One or more arguments supplied in the request is invalid.",
  "links" : [ {
    "href" : "https://xxxxxxxxxxxxxxxxxx:3780/api/3/tags?size=100&page=0",
    "rel" : "self"
  } ]
}

this works :  New-NexposeTag -Name "test" -Type "Custom" -Colour 'Default" -Debug

Update,  by looking at Owners tags created by the web inteface,  the proper tag for owners is  "owner" and not "owners".  The web inferface shows the label called "**owners**" simply because multiple owners can be assigned to an asset ID.  

I changed line line 44 of New-NexposeTags.ps1          [ValidateSet('Custom', 'Location', '**Owner**')]

And I am now able to create tags of type owner

**Comment by My-Random-Thoughts** [comment]
Thank you for reporting this, it looks like a type.  It should have been "Owner" and not "Owners".
