### ISSUE TITLE
token for authentication

### ISSUE THREAD

**Issue by animatco** [My-Random-Thoughts/Rapid7Nexpose#15]
Good Day and thank you for writing this module. I have an enhancement request. Could you add to the 'Connect-NexposeAPI' an option to use a token for authentication.

**Comment by My-Random-Thoughts** [comment]
I can try, I have no way of testing the code so if you you don't mind, can you be my tester?!  It should be fairly simple.
Add the following code please to your copy:

In the `Param` section at like 52, add:
`
         [string]$AuthToken,
`

Starting at line 85, after the `$invokeWebRequest += @{` block add the following three lines:
`            If ([string]::IsNullOrEmpty($AuthToken) -eq $false) {
                $invokeWebRequest += @{Token = $AuthToken}
            }
`

That should hopefully be right, the API suggests that is all that is needed.

**Comment by animatco** [comment]
I used your connect script as the basis for this:

`Function Connect-InSightVM {
    [CmdletBinding(SupportsShouldProcess)]
    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidGlobalVars', '', Scope = 'Function')]
    Param (
        [Parameter(Mandatory = $true)]
        [string]$HostName,

        [int]$Port = 3780,

        [Parameter(Mandatory = $true)]
        [string]$Token,

        [switch]$SkipSSLCheck
    )

    Begin {
        $invokeWebRequest = @{
            ErrorAction = 'Stop'
        }

        If ($SkipSSLCheck.IsPresent) {
            If ($PSVersionTable.PSVersion.Major -le 5) {
                [void](Skip-SSLError)
            }
            Else {
                $invokeWebRequest += @{ SkipCertificateCheck = $($SkipSSLCheck.IsPresent) }
            }
        }
    }

    Process {
        If ($PSCmdlet.ShouldProcess("$($HostName):$Port")) {
            [string]$authInfo = $Token

            $invokeWebRequest += @{
                Uri     = "https://$($HostName):$($Port)/api/3/"
                Method  = 'Get'
                Headers = @{Authorization = $authInfo}
            }

            $iWebReq = (Invoke-WebRequest @invokeWebRequest -SessionVariable global:NexposeSession )

            # Add extra header information
            $global:NexposeSession.Headers.Add('HostName',   $HostName               )
            $global:NexposeSession.Headers.Add('Port',       $Port                   )
            $global:NexposeSession.Headers.Add('SkipSSL',  $($SkipSSLCheck.IsPresent))

            Write-Verbose "Connection Status: $($iWebReq.statusCode) $($iWebReq.statusDescription)"
            Return $iWebReq
        }
    }

    End {
    }
}`

and I was able to connect. I hope that helps a little.

Steve

**Comment by My-Random-Thoughts** [comment]
That reads that you are not using a username/password, it's just a token code.  How does it know which user account to use?

Also, the line `[string]$authInfo = $Token` is not need, just use `Headers = @{Authorization = $Token}`

**Comment by animatco** [comment]
The token has that built in for Authentication.

**Comment by animatco** [comment]
I was just trying to test, it was not supposed to be final version. It
would be better if your code could have require  PSCredential or Token.
That should account for both scenarios.

**Comment by My-Random-Thoughts** [comment]
> would be better if your code could have require  PSCredential or Token.
I can't according to the API:

> This API supports two-factor authentication (2FA) by supplying an authentication token **in addition to** the Basic Authorization

It's on this page, under the 2FA section: https://help.rapid7.com/insightvm/en-us/api/index.html#section/Overview/Specification

**Comment by My-Random-Thoughts** [comment]
Closed due to inactivity.  Happy to reopen if you can do some testing
