### ISSUE TITLE
functionality: tags/{id}/assets 

### ISSUE THREAD

**Issue by NetherSmash** [My-Random-Thoughts/Rapid7Nexpose#19]
Thank you for the awesome project! It has already saved me countless hours :)

I note this from your documentation for Get-NexposeTag.ps1
> GET: SKIPPED - tags/{id}/assets             # Due to data already present in return object

This is supposed to return all assets with the tag {id}. However, I do not see a way to retrieve this "data already present". I've gone thru your code and can't see how to return this data. Any help (or added example) would be helpful and appreciated.

thanks
m

**Comment by My-Random-Thoughts** [comment]
Hi Nether, thanks for using my module.
I should make the comment a bit clearer  :)

To get a list of assets by tag, use `Get-NexposeAsset -Tag 'High' -TagType 'Criticality'`

You can also use this function to search by Group, Site or InstalledSoftware

**Comment by NetherSmash** [comment]
Very nice. Worked like a charm! thank you
