### ISSUE TITLE
Remove-NexposeTagFromObject  error 404

### ISSUE THREAD

**Issue by j-kest** [My-Random-Thoughts/Rapid7Nexpose#21]
**Describe the bug**
when running Remove-NexposeTagFromObject we get the following error.
"
Remove-NexposeTagFromObject -ObjectType Assets -ObjectId $assetid -TagId $idowner
The remote server returned an error: (404) Not Found.
{
  "status" : 404,
  "message" : "The requested resource does not exist. Please consult the documentation for available resources.",
  "links" : [ {
    "href" : https://insightvm/api/3/Assets/1927/tags/39,
    "rel" : "self"
  } ]
}
At line:185 char:13
+             Throw "`n$errMsg1`n$errMsg2`n$errMsg3"
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (
The remote ser...elf"
  } ]
}
:String) [], RuntimeException
    + FullyQualifiedErrorId : 
The remote server returned an error: (404) Not Found.
{
  "status" : 404,
  "message" : "The requested resource does not exist. Please consult the documentation for available resources.",
  "links" : [ {
    "href" : https://insightvm/api/3/Assets/1927/tags/39,
    "rel" : "self"
  } ]
} 
" 

**To Reproduce**
We had contact with rapid7 and according to them uri should be https://insightvm/api/3/tags/39/assets/1900/ and not 
https://insightvm/api/3/Assets/1900/tags/39
how can we fix this?

**Comment by My-Random-Thoughts** [comment]
Thanks for reporting this, but according to the documentation it should be fine: https://help.rapid7.com/insightvm/en-us/api/index.html#operation/removeAssetTag

That would suggest that their documentation is wrong if that is not correct - not the first time this has happened!
To fix this, I would need to rewrite the function to use the `/tag/` URI.

**Comment by j-kest** [comment]
Hey, there support referred to this link:
https://help.rapid7.com/insightvm/en-us/api/index.html#operation/untagAsset

**Comment by My-Random-Thoughts** [comment]
Yea that is just the opposite of the one I am using.
    : `/api/3/assets/{id}/tags/{tagId}`
    : `/api/3/tags/{id}/assets/{assetId}`

Going by the 404 error message, it suggests that the documentation is wrong and that endpoint is no longer valid - it was when I wrote it.

**Comment by j-kest** [comment]
that was my fear. is this something that you can easily fix?

**Comment by My-Random-Thoughts** [comment]
It should be fairly easy to fix, just a matter to swapping a few things. 
I may not be able to get to until quickly though.

**Comment by j-kest** [comment]
Hi so according to them both work. but there is an error in the uri. with the powershell it uses Assets with capital "A" and it should be a lower case "a"

**Comment by My-Random-Thoughts** [comment]
That's interesting.  My function doesn't use a capital A.
Can you run your command again, but add `-Verbose` to the end and send me the output please (removing any company specific info of course)

**Comment by j-kest** [comment]
found it. it was in the powershell line : Remove-NexposeTagFromObject -ObjectType Assets -ObjectId $assetid -TagId $idowner
replacing it with : "Remove-NexposeTagFromObject -ObjectType assets -ObjectId $assetid -TagId $idowner" does the trick it seems

**Comment by My-Random-Thoughts** [comment]
Ah so it was your fault  :)
I'll add a note to ensure inputs are set to lowercase where required.

Are you happy this is fixed?

**Comment by j-kest** [comment]
yes 100%! thanks for helping me with the right info to get the support on the right track 😄
