### ISSUE TITLE
Enabling credentials expects lower case true/false

### ISSUE THREAD

**Issue by NetherSmash** [My-Random-Thoughts/Rapid7Nexpose#22]
in the call for sites/$SiteId/shared_credentials/$CredId/enabled, the API expects the body to be "true" or "false" in lower case. The current code throw an error:

Set-NexposeSiteCredentialEnablement -CredId 39 -SiteId 421 -IsSharedCredential -Enable -Verbose
VERBOSE: Performing the operation "Set-NexposeSiteCredentialEnablement" on target "421-39".
VERBOSE: Executing API method "PUT" against "/api/3/sites/421/shared_credentials/39/enabled"
VERBOSE: PUT https://server:3780/api/3/sites/421/shared_credentials/39/enabled with -1-byte payload
The remote server returned an error: (400) Bad Request.
{
  "status" : 400,
  "message" : "The JSON input is invalid at line 1, column 5. Details: Unrecognized token 'True': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false').",
  "links" : [ {
    "href" : "https://server:3780/api/3/sites/421/shared_credentials/39/enabled",
    "rel" : "self"
  } ]
}
At line:184 char:13
+             Throw "`n$errMsg1`n$errMsg2`n$errMsg3"
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (
The remote ser..."self"
  } ]
}
:String) [], RuntimeException
    + FullyQualifiedErrorId : 
The remote server returned an error: (400) Bad Request.
{
  "status" : 400,
  "message" : "The JSON input is invalid at line 1, column 5. Details: Unrecognized token 'True': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false').",
  "links" : [ {
    "href" : "https://server:3780/api/3/sites/421/shared_credentials/39/enabled",
    "rel" : "self"
  } ]
}

Editing the Begin block in Set-NexposeSiteCredentialEnablement.ps1 fixes the error:
    Begin {
        If ($PSCmdlet.ParameterSetName -eq 'byEnabled' ) { [string]$Setting = '**true**'  }
        If ($PSCmdlet.ParameterSetName -eq 'byDisabled') { [string]$Setting = 'false' }
    }

**Comment by My-Random-Thoughts** [comment]
Thank you for reporting this, now fixed.
