### ISSUE TITLE
New-NexposeSiteScanSchedule.ps1 fails when adding $converted to $apiQuery

### ISSUE THREAD

**Issue by NetherSmash** [My-Random-Thoughts/Rapid7Nexpose#23]
When adding a new site scan schedule, teh code fails as some keys in $concerted already exist in $apiQuery

```
New-NexposeSiteScanSchedule `
    -SiteId $site.id `
    -Name $name `
    -Duration $durationInSeconds `
    -ScanRepeat restart-scan `
    -StartDateTime $startDateTime `
    -Frequency "Every First Tuesday of the Month" `
    -scanTemplate "full-audit" `
    -Enabled:$true `
```

returns error:

```
Item has already been added. Key in dictionary: 'enabled'  Key being added: 'enabled'
At line:129 char:37
+         If ($null -ne $converted) { $apiQuery += $converted}
+                                     ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException
```
A couple options to fix: Editing line 129 from
```
        If ($null -ne $converted) { $apiQuery += $converted}```
to
```
  #add new values

        If ($null -ne $converted) {
            $converted.Keys | Where { $_ -notin $ApiQuery.Keys } | % { 
                Write-Verbose "Adding '$($_.Name)' to apiQuery"
                $ApiQuery.Add($_, $converted[$_])
            }  
        }  
```
or line 128-129 to
```
        If ($null -ne $converted) { 
            # add and update values
            $converted.GetEnumerator() | % { 
                if (-not $apiQuery.ContainsKey($_.Name)) {
                    Write-Verbose "Adding '$($_.Name)' to apiQuery"
                    $apiQuery.Add($_.name, $_.Value)
                }
                else {
                    Write-Verbose "Updating '$($_.Name)' in apiQuery"
                    $apiQuery[$_.name] = $_.Value
                }
            }
        }
```

**Comment by My-Random-Thoughts** [comment]
Thank you again for your issue entry.  You take the time to provide a fix and saves me a lot of work - I have not touched most of this code in a while!

I'll have a closer look at this over the weekend.

**Comment by My-Random-Thoughts** [comment]
Doing some testing, your `Frequency` parameter is not correct.

     "Every First Tuesday of the Month"

change to 

    "Every 1st Tuesday of the Month"


I couldn't reproduce the error message you got.  I'll keep testing.

**Comment by My-Random-Thoughts** [comment]
I have now just added support for "first", "second", ...
I didn't realise it was missing yet added as an example.

**Comment by NetherSmash** [comment]
Thanks for the quick fix. The scans add now, but I'm still getting an error:

```
Item has already been added. Key in dictionary: 'enabled'  Key being added: 'enabled'
At line:129 char:37
+         If ($null -ne $converted) { $apiQuery += $converted}
+                                     ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException
```
$apiQuery has this key, and it's also returned in $converted

**Comment by My-Random-Thoughts** [comment]
Very strange.  As you can see here https://github.com/My-Random-Thoughts/Rapid7Nexpose/blob/master/private/Convert-FrequencyString.ps1#L94C10-L94C18, the `$apiQuery` does not contain the `enabled` key.

On your local copy, try changing that line to `$apiQuery = @{ repeat = @{} }`  (change `+=` to `=`) just in case something is being copied back and forth between the functions.

**Comment by NetherSmash** [comment]
for whatever reason that new file (Convert-FrequencyString.ps1) does not download. I've even removed and reinstalled to no avail.  It's still dated 2021-04-07. But if I manually copy the code, it works great.  Thanks

**Comment by My-Random-Thoughts** [comment]
Strange.
Are you now saying that your problem is fixed?

**Comment by NetherSmash** [comment]
I tried on a fresh system. The new file does not pull; still dated 2021-04-07
Not sure if it's a commit/versioning issue or what.

**Comment by My-Random-Thoughts** [comment]
Where are you pulling from?
I don't do branches or other "fancy" github stuff, just edit/change in main.  :)
I've just done a "Download ZIP" from github and it has the newest files.

There is an old version on the PowerShell Gallery, I really should update that at some point.

**Comment by NetherSmash** [comment]
No need for fancy :)
That's how I was pulling it down from... install-module

**Comment by My-Random-Thoughts** [comment]
Ah, the PowerShell gallery is not up to date.  Pull it from there if you like, but then over write the files with the ones on GitHub.

**Comment by NetherSmash** [comment]
Oh having the gallery up to date would be a plus for sure. But I don't know what that entails.
  thx you can close this now
