### ISSUE TITLE
-Count parameter in Invoke-NexposeQuery

### ISSUE THREAD

**Issue by NetherSmash** [My-Random-Thoughts/Rapid7Nexpose#25]
I have script that alerts Rapid7 admins to tags with 0 assets, with future plans to auto delete them instead. However, tags with large counts take a really long time to grab all the resources. There is something really slowing down the process. I've noticed before when trying to retrieve all assets (`$allAssets = Get-NexposeAsset`), but I've gotten around this by just creating a report and downloading that instead. I am happy to test various number of resources being returned to see if the delay is linear or exponential - let me know

a call like this will often take 15-20 minutes:
`$assets = Get-NexposeAsset -Tag "Tag with 3000 assets" -TagType Custom`

Digging into this slowness, I noticed that `Invoke-NexposeQuery` has a Count parameter. This would be ideal for my tag issue. I added the Count parameter to `Get-NexposeAsset` and passed it to `Invoke-NexposeQuery`, and while the code `If ($Count.IsPresent) {` on line 135 executed properly, nothing (`$null`) was returned to the calling function.

1) Was `-Count` preparing for future functionality in the public functions? 
2) Any idea why large number of objects is really slow?

thx

**Comment by NetherSmash** [comment]
My code to add the Count switch to Get-NexposeAsset

`        [Parameter(ParameterSetName = 'byId')]`
`        [Parameter(ParameterSetName = 'byName')]`
`        [Parameter(ParameterSetName = 'byGroup')]`
`        [Parameter(ParameterSetName = 'byIPAddress')]`
`        [Parameter(ParameterSetName = 'bySoftware')]`
`        [Parameter(ParameterSetName = 'bySite')]`
`        [Parameter(ParameterSetName = 'byTag')]`
`        [switch]$Count`

and my calling line
`[object]$assetData = @(Invoke-NexposeQuery -UrlFunction 'assets/search' -ApiQuery $apiQuery -RestMethod Post -Count:$Count)`

**Comment by My-Random-Thoughts** [comment]
Hi.  I can't remember why `Count` was added, it was done [quite a while ago](https://github.com/My-Random-Thoughts/Rapid7Nexpose/commit/51b82ddf57f77f9befcf83ca37a5fc23dce8ea17).  I have searched the code and can't see why I added it in - it's not used anywhere!

I'll do some digging this weekend and have a look.

**Comment by My-Random-Thoughts** [comment]
OK, give that a go.  Changed just `Get-NexposeAsset` to enable `-Count`

**Comment by NetherSmash** [comment]
Super!

`$cmd = Measure-Command { $AssetCount = Get-NexposeAsset -Tag 271 -TagType Owner -Count -Verbose }`
`Write-Host "Execution time $($cmd.TotalSeconds) second"`
`Write-Host "Total assets $AssetCount"`

VERBOSE: Executing API method "GET" against "/api/3/tags/271?size=100"
VERBOSE: GET https://sls9017.stholdco.com:3780/api/3/tags/271?size=100 with 0-byte payload
VERBOSE: received -1-byte response of content type application/json;charset=UTF-8
VERBOSE: Removing "links" item from results
VERBOSE: Executing API method "POST" against "/api/3/assets/search?size=100&page=0"
VERBOSE: POST https://sls9017.stholdco.com:3780/api/3/assets/search?size=100&page=0 with -1-byte payload
VERBOSE: received -1-byte response of content type application/json;charset=UTF-8
VERBOSE: Removing "links" item from results
Execution time 14.5382366 second
Total assets 2154


As always, I appreciate the quick turnaround. I'm not sure why it didn't work for me, whether I included all the ParameterSetNames or not.

**Comment by NetherSmash** [comment]
I'll at some point about digging into the slowness of returning large numbers of resources, as mentioned in the original issue 

`$Assets = Get-NexposeAsset -Tag 271 -TagType Owner`

But if/when I find something related to the module and not the API itself, I'll post a new issue. Thx again!
