### ISSUE TITLE
Get-NexposeVulnerabilityCategory - called function does not exist

### ISSUE THREAD

**Issue by NetherSmash** [My-Random-Thoughts/Rapid7Nexpose#26]
The function on line 46 does not exist:
`            $vulnCat.vulnerabilities += (Get-NexposeVulnerability -Id $vuln)`

You already easily call for the nexpose_ids, so just insert them if the switch isn't present since the call doesn't take much time. If the switch is present, call the correct function and return all details. Something like:

`        $vulns = @(Invoke-NexposeQuery -UrlFunction "vulnerability_categories/$Id/vulnerabilities" -RestMethod Get)`
`        If ($IncludeVulnerabilities.IsPresent) {`
`            $vulnCat | Add-Member -NotePropertyName 'vulnerabilities' -NotePropertyValue $vulns`
`        }`
`        Else {`
`            ForEach ($vuln In $vulns) {`
`                $vulnCat.vulnerabilities += (Get-NexposeVulnerabilityItem -Id $vuln)`
`            }`
`        }`

**Comment by My-Random-Thoughts** [comment]
Thanks, I think it should be `$vulnCat.vulnerabilities += (Get-NexposeVulnerabilityItem -Id $vuln)`

**Comment by NetherSmash** [comment]
Yes, I believe that is what you intended.

However, my suggested code means the vulnerability nexpose_ids are always returned, which would often be enough for the caller. And the switch would then return full details of each vulnerability.

**Comment by My-Random-Thoughts** [comment]
OK, I liked your idea and it does not take as much time as I thought.

I have renamed the parameter though to `IncludeVulnerabilityDetail` as it's a better name for it now.

Thank you

**Comment by NetherSmash** [comment]
I'm happy to see that :)
