### ISSUE TITLE
Allow only Asset ID's reported when using Get-NexposeAsset

### ISSUE THREAD

**Issue by VXH5** [My-Random-Thoughts/Rapid7Nexpose#27]
When using Get-NexposeAsset it calls Get-NexposeAsset again for each AssetID it recieves to gather more info before returning the info. In my use case, I'd prefer to just recieve the asset ID's, to then be processed in a script like calling Update-NexposeTag, or Get-NexposeAssetVulnrebility further down the line.

To Achieve this; I've edited Get-NexposeAsset.ps1 in the below way
New Switch:

          [Parameter(Mandatory = $true, ParameterSetName = 'byGroup')]
          [switch]$IDonly

Editing the Group portion:

          'byGroup' {
              $Group = (ConvertTo-NexposeId -Name $Group -ObjectType 'AssetGroup')
              If (-not $Group) { Throw 'Invalid group name or id' }
              [object]$assets = @(Invoke-NexposeQuery -UrlFunction "asset_groups/$Group/assets" -RestMethod Get -Count$Count.IsPresent)
  
              If ($Count.IsPresent) {
                  Write-Output $assets[0]
              }
              ElseIf ([string]::IsNullOrEmpty($assets) -eq $false) {
                  If ($IDonly.IsPresent) {
                      Write-Output $assets
                  }
                  else {
                      ForEach ($id In $assets) {
                          Write-Output (Get-NexposeAsset -Id $id)
                      }
                  }
              }
          }

**Comment by My-Random-Thoughts** [comment]
Thanks VXH5 for reporting your issue.

Is there much of a speed improvement in doing this?
I realise obviously it's performing a second API call, but the results may already be cached and return faster.

If you could use a `Measure-Command` on your changes to see how much of a difference there is please.  I only have 5 or 6 assets so my results won't count :)

I don't see an issue in adding the additional switch, but almost all other PowerShell commands return all data and leave the property filtering to the user.

**Comment by VXH5** [comment]
Hi,
It adds up to a big difference. For a ~300 asset group with the IDOnly it runs in 250ms vs. 35 seconds. And some of our groups are in the thousands so can take minutes vs. seconds. Granted these tests are over a remote connection. But I've had cases where it's timed out when run locally.
Realised I'd made a mistake with my parameter set above, and it's broken -count, the intention was to only allow -IDOnly when using the group.

**Comment by My-Random-Thoughts** [comment]
Thanks, that is a big difference.  I'll have a look at adding this tomorrow - I would have checked the `-Count` code too  :)

**Comment by VXH5** [comment]
Great. Your work here is much appreciated; has saved us a lot of time and effort.

**Comment by My-Random-Thoughts** [comment]
Added '-IdsOnly' parameter, give that a go.
