### ISSUE TITLE
 Port/PortRestriction parameter evaluation and validation

### ISSUE THREAD

**Issue by NetherSmash** [My-Random-Thoughts/Rapid7Nexpose#29]
### Parameter Evaluation
Port parameter is not properly evaluated on line 58 in Update-NexposeScanEngine, and the API call fails

` If ([string]::IsNullOrEmpty($Port)    -eq $true) { $Port    = $engine.port    }`

should be something like

` If ($Port    -eq 0) { $Port    = $engine.port    }  { $Port    = $engine.port    }`

similar to Update-NexposeSite.ps1

` If (                        $EngineId        -eq 0    ) { $EngineId       = $site.scanEngine   }`

I did a quick search and don't believe any other [int] params are passed  that need validation

### Parameter Validation
The following param blocks should also have [ValidateRange(1, 65535)] to be consistent with other functions

- Connect-NexposeAPI.ps1
- Get-NexposeAssetService.ps1
- New-NexposeScanEngine.ps1 (has validation)
- New-NexposeSharedCredential.ps1 (has validation)
- New-NexposeSiteCredential.ps1 (has validation)
- Update-NexposeScanEngine
- Update-NexposeSharedCredential.ps1 (has validation)
- Update-NexposeSiteCredential.ps1 (has validation)

thx

**Comment by My-Random-Thoughts** [comment]
All fixed, thank you for spotting those!
