### ISSUE TITLE
Authentication fails

### ISSUE THREAD

**Issue by hhonermann** [My-Random-Thoughts/Rapid7Nexpose#3]
Hi,

we're using Nexpose in a German Bank. Your PowerShell Module looks very interesting to us and we would like to use it to automize some processes.

I successfully installed the module on our Nexpose Security Console server (running Windows Server 2012). Unfortunately I am not able to authenticate with 'Connect-NexposeAPI' command. I always get the following error message:

PS C:\Windows\System32\WindowsPowerShell\v1.0> Connect-NexposeAPI -HostName ‘127.0.0.1' -Port '3780' -SkipSSLCheck
cmdlet Connect-NexposeAPI at command pipeline position 1
Supply values for the following parameters:
Credential
          <<< here I entered username / password of a valid Nexpose GUI user >>>
Invoke-WebRequest : The underlying connection was closed: An unexpected error occurred on a receive.
At line:64 char:13
+             Invoke-WebRequest -Uri "https://$($HostName):$($Port)/api ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
PS C:\Windows\System32\WindowsPowerShell\v1.0>

Any idea, why I can't connect?

Many thanks in advance,

Helmut Honermann
email: helmut.honermann@puresec.de

**Comment by My-Random-Thoughts** [comment]
Try setting your security protocol type to a higher level, it may not be correct.

To see the current level, use `[Net.ServicePointManager]::SecurityProtocol`
To set a specific level, use `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`

You can set multiple levels, have a look at this page for more information:
https://stackoverflow.com/questions/36265534/invoke-webrequest-ssl-fails

**Comment by hhonermann** [comment]
Many thanks for the prompt answer. This was the right idea. Now the connection is working.
Best regards
Helmut
