### ISSUE TITLE
Update-NexposeSiteAlert returns 400 Bad Request

### ISSUE THREAD

**Issue by andreajeka** [My-Random-Thoughts/Rapid7Nexpose#5]
Hi I always receive an error when I try to run this API command

`Update-NexposeSiteAlert -Enabled -ScanStopped -ScanFailed -NotificationType 'SMTP' -EmailServer 'xxxsmtp.corp.company.com' -SiteId 327 -Name 'Stopped or Failed Scan' -SenderEmailAddress 'xxx@company.com' -SMTPRecipients 'xxx@company.com' -VulnerabilitySeverity 'only_critical'`

Error Message:
![image](https://user-images.githubusercontent.com/8019899/84347468-3697cd00-abe5-11ea-84de-54bc75bbcad6.png)

How can I fix this?

Thanks,
Andrea

**Comment by My-Random-Thoughts** [comment]
Hey Andrea, can you add `-Verbose` to the end of the command please, it should show the JSON that is being passed to the API.  Clear out any company specific data of course.  Thanks

**Comment by andreajeka** [comment]
Here you go!

![image](https://user-images.githubusercontent.com/8019899/84508403-ca0bf380-acf4-11ea-9723-52c60a00aca0.png)

**Comment by My-Random-Thoughts** [comment]
Hey, I have applied an update to Update-NexposeSiteAlert to fix the issue.  See if that works for you.  It's not ideal and I'll be looking at getting it fixed properly.

**Comment by My-Random-Thoughts** [comment]
Looking at this again, it looks like what I thought was happening, wasn't.  I am mot going to implement the endpoints `/api/3/sites/{id}/alerts/...` which allows the updating of multiple alerts in one go.  Updating one at a time still works, but not many.

The reason for this is the API will remove any alerts that are not set in the update list: "Array of resources for updating all SNMP alerts defined in the site. Alerts defined in the site that are omitted from this request will be deleted from the site."  This could mean that you only specify two alerts to update thinking that only they will change, they will, but any other alert configured will be deleted.

I'll mark this as "wont fix" for this reason and remove the workaround that I had in place.
