### ISSUE TITLE
Invoke-WebRequest TLS Issue and UseBasicParsing

### ISSUE THREAD

**Issue by mt-fort** [My-Random-Thoughts/Rapid7Nexpose#6]
### TLS
In our environment, we have disabled TLS 1.0 and 1.1 and by default PowerShell uses TLS 1.0 therefore when I tried to connect to the API, it would fail with error "Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel"

To fix this, I had to force TLS 1.2 connection and added a code before line 64 in Connect-NexposeAPI:
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

Error reference: https://stackoverflow.com/questions/41618766/powershell-invoke-webrequest-fails-with-ssl-tls-secure-channel

### UseBasicParsing Flag
I ran to another error with the parsing for IE, and added the  -UseBasicParsing flag in Invoke-WebRequest which resolved it.

**Modified Code:**
 [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
            $iWebReq = (Invoke-WebRequest -Uri "https://$($HostName):$($Port)/api/3/" -Method Get `
                -Headers @{Authorization = ('Basic {0}' -f $authInfo)} `
                -SessionVariable global:NexposeSession `
                -ErrorAction Stop `
                -UseBasicParsing
            )

Great work on the API, only scratching the surface on what we're doing but already helps alot.

**Comment by My-Random-Thoughts** [comment]
Thanks for the feedback.

The TLS "issue" is a known one and is covered in the closed issue #3 .
I am not forcing it (I could I suppose) but each company is different so they should handle it internally.  I actually have the line mentioned in #3 in my profile script, so I usually forget about it  :)

I'll add `UseBasicParsing`.  I have not seen an issue, but I do usually add it in other code.  I am calling `Invoke-WebRequest` in a couple of other scripts, so I'll change those too.

**Comment by My-Random-Thoughts** [comment]
The `UseBasicParsing` should be fixed now, I changed the way I was calling the code - it's not centralised.
